// Static data for AddManuChain Dashboard

export const users = [
  { id: 'user-1', email: 'j.operator@horizonmaritime.com', name: 'John Operator', role: 'operator', company: 'Horizon Maritime' },
  { id: 'user-2', email: 's.chen@noblecorp.com', name: 'Sarah Chen', role: 'manager', company: 'Noble Corp' },
  { id: 'user-3', email: 'm.johnson@equinor.com', name: 'Mike Johnson', role: 'operator', company: 'Equinor' },
  { id: 'user-4', email: 'd.brown@rosenmaritime.com', name: 'David Brown', role: 'manager', company: 'Rosen Maritime' },
  { id: 'user-5', email: 'l.wang@thales.ca', name: 'Lisa Wang', role: 'procurement', company: 'Thales Canada' },
]

export const blueprints = [
  { id: 'bp-1', blueprintId: 'BP-1024', name: 'Thruster Bearing Housing', category: 'Structural', material: 'Titanium Ti-6Al-4V', oem: 'Rosen Maritime', certification: "Lloyd's Register", status: 'active', printCount: 47, description: 'High-performance thruster bearing housing for marine propulsion systems' },
  { id: 'bp-2', blueprintId: 'BP-0892', name: 'Hydraulic Valve Body', category: 'Hydraulic', material: 'Stainless Steel 316L', oem: 'Noble Corp', certification: 'DNV GL', status: 'active', printCount: 23, description: 'Precision hydraulic valve body for offshore equipment' },
  { id: 'bp-3', blueprintId: 'BP-0456', name: 'Sensor Mounting Bracket', category: 'Structural', material: 'Aluminum 6061-T6', oem: 'Equinor', certification: 'Self-certified', status: 'active', printCount: 156, description: 'Universal sensor mounting bracket for marine environments' },
  { id: 'bp-4', blueprintId: 'BP-0789', name: 'Impeller Shaft', category: 'Rotating', material: 'Inconel 718', oem: 'Thales', certification: "Lloyd's Register", status: 'pending_review', printCount: 12, description: 'High-strength impeller shaft for pump systems' },
  { id: 'bp-5', blueprintId: 'BP-0334', name: 'Heat Exchanger Plate', category: 'Thermal', material: 'Copper C18150', oem: 'Cove', certification: 'DNV GL', status: 'active', printCount: 89, description: 'Heat exchanger plate for thermal management systems' },
  { id: 'bp-6', blueprintId: 'BP-0667', name: 'Pressure Housing Seal', category: 'Seals', material: 'H13 Tool Steel', oem: 'Rosen Maritime', certification: 'DNV GL', status: 'active', printCount: 34, description: 'High-pressure housing seal for subsea applications' },
  { id: 'bp-7', blueprintId: 'BP-0123', name: 'Motor Coupling Flange', category: 'Coupling', material: 'Steel 4340', oem: 'Horizon Maritime', certification: 'Self-certified', status: 'active', printCount: 78, description: 'Motor coupling flange for power transmission' },
  { id: 'bp-8', blueprintId: 'BP-0555', name: 'Control Panel Enclosure', category: 'Electrical', material: 'Aluminum 6061-T6', oem: 'Ecotex', certification: 'CSA', status: 'inactive', printCount: 5, description: 'Control panel enclosure for electrical systems' },
  { id: 'bp-9', blueprintId: 'BP-0556', name: 'Hydraulic Cylinder Rod', category: 'Hydraulic', material: 'Steel 4340', oem: 'Bosch Rexroth', certification: 'DNV GL', status: 'active', printCount: 45, description: 'Hydraulic cylinder rod for offshore equipment' },
  { id: 'bp-10', blueprintId: 'BP-0557', name: 'Propeller Blade Tip', category: 'Rotating', material: 'Titanium Ti-6Al-4V', oem: 'Wärtsilä', certification: "Lloyd's Register", status: 'active', printCount: 67, description: 'Propeller blade tip for marine propulsion' },
  { id: 'bp-11', blueprintId: 'BP-0558', name: 'Exhaust Valve Seat', category: 'Thermal', material: 'Inconel 718', oem: 'MAN Energy', certification: 'DNV GL', status: 'active', printCount: 34, description: 'Exhaust valve seat for engine systems' },
  { id: 'bp-12', blueprintId: 'BP-0559', name: 'Anchor Chain Link', category: 'Structural', material: 'Stainless Steel 316L', oem: 'Viking Norsafe', certification: "Lloyd's Register", status: 'active', printCount: 89, description: 'Anchor chain link for mooring systems' },
]

export const printCenters = [
  { id: 'pc-1', centerId: 'PC-001', name: 'Atlantic XL', location: 'Halifax, NS', status: 'online', certification: "Lloyd's Register", totalPrinters: 6, activePrinters: 5, capacity: 87, currentJobs: 8, completedToday: 12, contactName: 'Robert Mackenzie', contactEmail: 'rmackenzie@atlanticxl.ca', materials: ['Titanium Ti-6Al-4V', 'Stainless Steel 316L', 'Aluminum 6061-T6'], specialties: ['Marine Components', 'Structural Parts'] },
  { id: 'pc-2', centerId: 'PC-002', name: 'DNV Calgary', location: 'Calgary, AB', status: 'online', certification: 'DNV GL', totalPrinters: 4, activePrinters: 4, capacity: 92, currentJobs: 6, completedToday: 8, contactName: 'Sarah Thompson', contactEmail: 'sthompson@dnvcalgary.com', materials: ['Inconel 718', 'H13 Tool Steel', 'Steel 4340'], specialties: ['Oil & Gas Components', 'High-temp Parts'] },
  { id: 'pc-3', centerId: 'PC-003', name: 'LR Montreal', location: 'Montreal, QC', status: 'busy', certification: "Lloyd's Register", totalPrinters: 5, activePrinters: 5, capacity: 98, currentJobs: 12, completedToday: 5, contactName: 'Jean-Pierre Dubois', contactEmail: 'jpdubois@lrmontreal.ca', materials: ['Titanium Ti-6Al-4V', 'Copper C18150', 'Stainless Steel 316L'], specialties: ['Thermal Components', 'Heat Exchangers'] },
  { id: 'pc-4', centerId: 'PC-004', name: "St. John's AM", location: "St. John's, NL", status: 'offline', certification: 'DNV GL', totalPrinters: 3, activePrinters: 0, capacity: 0, currentJobs: 0, completedToday: 0, contactName: "Michael O'Brien", contactEmail: 'mobrien@stjohnsam.ca', materials: ['Aluminum 6061-T6', 'Steel 4340'], specialties: ['Remote Support', 'Emergency Parts'] },
  { id: 'pc-5', centerId: 'PC-005', name: 'Victoria Marine', location: 'Victoria, BC', status: 'online', certification: 'CSA', totalPrinters: 4, activePrinters: 3, capacity: 65, currentJobs: 4, completedToday: 6, contactName: 'Emily Wong', contactEmail: 'ewong@victoriamarine.ca', materials: ['Stainless Steel 316L', 'Aluminum 6061-T6', 'Copper C18150'], specialties: ['Naval Components', 'Electrical Enclosures'] },
]

export const orders = [
  { id: 'ord-1', orderId: 'ORD-2847', partName: 'Thruster Bearing Housing', status: 'printing', priority: 'high', quantity: 2, eta: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-1', blueprintId: 'bp-1', centerId: 'pc-1', notes: null, createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-2', orderId: 'ORD-2846', partName: 'Hydraulic Valve Body', status: 'quality_check', priority: 'medium', quantity: 1, eta: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-2', blueprintId: 'bp-2', centerId: 'pc-2', notes: null, createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-3', orderId: 'ORD-2845', partName: 'Sensor Mounting Bracket', status: 'shipped', priority: 'low', quantity: 5, eta: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-3', blueprintId: 'bp-3', centerId: 'pc-1', notes: null, createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-4', orderId: 'ORD-2844', partName: 'Impeller Shaft', status: 'pending', priority: 'high', quantity: 1, eta: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-1', blueprintId: 'bp-4', centerId: null, notes: 'Rush order for offshore platform', createdAt: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-5', orderId: 'ORD-2843', partName: 'Heat Exchanger Plate', status: 'delivered', priority: 'medium', quantity: 3, eta: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-2', blueprintId: 'bp-5', centerId: 'pc-3', notes: null, createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-6', orderId: 'ORD-2842', partName: 'Pressure Housing Seal', status: 'printing', priority: 'medium', quantity: 4, eta: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-1', blueprintId: 'bp-6', centerId: 'pc-1', notes: null, createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-7', orderId: 'ORD-2841', partName: 'Motor Coupling Flange', status: 'delivered', priority: 'low', quantity: 2, eta: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-3', blueprintId: 'bp-7', centerId: 'pc-2', notes: null, createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-8', orderId: 'ORD-2850', partName: 'Flange Connector', status: 'pending', priority: 'medium', quantity: 3, eta: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-4', blueprintId: null, centerId: null, notes: null, createdAt: new Date(Date.now()).toISOString() },
  { id: 'ord-9', orderId: 'ORD-2851', partName: 'Gasket Seal Ring', status: 'printing', priority: 'high', quantity: 10, eta: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-5', blueprintId: null, centerId: 'pc-5', notes: null, createdAt: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-10', orderId: 'ORD-2852', partName: 'Bearing Housing Cap', status: 'quality_check', priority: 'high', quantity: 2, eta: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-1', blueprintId: null, centerId: 'pc-3', notes: null, createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-11', orderId: 'ORD-2853', partName: 'Pump Impeller', status: 'shipped', priority: 'medium', quantity: 1, eta: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-2', blueprintId: null, centerId: 'pc-2', notes: null, createdAt: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-12', orderId: 'ORD-2854', partName: 'Valve Stem', status: 'delivered', priority: 'low', quantity: 5, eta: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-3', blueprintId: null, centerId: 'pc-1', notes: null, createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-13', orderId: 'ORD-2855', partName: 'Shaft Coupling', status: 'pending', priority: 'medium', quantity: 2, eta: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-4', blueprintId: null, centerId: null, notes: null, createdAt: new Date(Date.now()).toISOString() },
  { id: 'ord-14', orderId: 'ORD-2856', partName: 'Pipe Fitting Adapter', status: 'printing', priority: 'low', quantity: 8, eta: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-5', blueprintId: null, centerId: 'pc-5', notes: null, createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-15', orderId: 'ORD-2857', partName: 'Heat Sink Plate', status: 'quality_check', priority: 'medium', quantity: 4, eta: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-1', blueprintId: null, centerId: 'pc-3', notes: null, createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString() },
  { id: 'ord-16', orderId: 'ORD-2858', partName: 'Enclosure Bracket', status: 'shipped', priority: 'low', quantity: 6, eta: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), requesterId: 'user-2', blueprintId: null, centerId: 'pc-1', notes: null, createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString() },
]

export const shipments = [
  { id: 'ship-1', trackingId: 'AMC-001-2024', orderId: 'ord-1', status: 'in_transit', origin: 'Atlantic XL, Halifax NS', destination: "Horizon Maritime, St. John's NL", carrier: 'FedEx Priority', estimatedDelivery: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), actualDelivery: null, distance: 1150, progress: 65 },
  { id: 'ship-2', trackingId: 'AMC-002-2024', orderId: 'ord-2', status: 'out_for_delivery', origin: 'DNV Calgary, Calgary AB', destination: 'Noble Corp, Edmonton AB', carrier: 'Purolator Express', estimatedDelivery: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toISOString(), actualDelivery: null, distance: 300, progress: 90 },
  { id: 'ship-3', trackingId: 'AMC-003-2024', orderId: 'ord-3', status: 'delivered', origin: 'Atlantic XL, Halifax NS', destination: "Equinor, St. John's NL", carrier: 'UPS Ground', estimatedDelivery: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), actualDelivery: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), distance: 1150, progress: 100 },
  { id: 'ship-4', trackingId: 'AMC-004-2024', orderId: 'ord-5', status: 'delivered', origin: 'LR Montreal, Montreal QC', destination: 'Cove, Edmonton AB', carrier: 'FedEx Ground', estimatedDelivery: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), actualDelivery: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), distance: 3500, progress: 100 },
  { id: 'ship-5', trackingId: 'AMC-005-2024', orderId: 'ord-6', status: 'in_transit', origin: 'Atlantic XL, Halifax NS', destination: "Rosen Maritime, St. John's NL", carrier: 'FedEx Priority', estimatedDelivery: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), actualDelivery: null, distance: 1150, progress: 45 },
  { id: 'ship-6', trackingId: 'AMC-006-2024', orderId: 'ord-7', status: 'delivered', origin: 'DNV Calgary, Calgary AB', destination: 'Horizon Maritime, Halifax NS', carrier: 'Purolator', estimatedDelivery: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), actualDelivery: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(), distance: 4500, progress: 100 },
  { id: 'ship-7', trackingId: 'AMC-007-2024', orderId: 'ord-8', status: 'preparing', origin: 'Atlantic XL, Halifax NS', destination: "Equinor, St. John's NL", carrier: 'FedEx Priority', estimatedDelivery: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000).toISOString(), actualDelivery: null, distance: 1150, progress: 10 },
  { id: 'ship-8', trackingId: 'AMC-008-2024', orderId: 'ord-9', status: 'delayed', origin: 'Victoria Marine, Victoria BC', destination: 'Thales, Ottawa ON', carrier: 'Canada Post', estimatedDelivery: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(), actualDelivery: null, distance: 4500, progress: 35 },
]

export const partners = [
  { id: 'partner-1', name: 'Rosen Maritime', email: 'partnerships@rosenmaritime.com', phone: '+1 902-555-0101', type: 'OEM', status: 'active', address: "St. John's, NL, Canada", notes: 'Key partner for thruster components', blueprints: 47, totalPrints: 1234, revenue: 185000, joinedDate: '2024-01-15' },
  { id: 'partner-2', name: 'Noble Corp', email: 'supply.chain@noblecorp.com', phone: '+1 403-555-0202', type: 'OEM', status: 'active', address: 'Calgary, AB, Canada', notes: 'Primary offshore drilling equipment supplier', blueprints: 32, totalPrints: 856, revenue: 128000, joinedDate: '2024-02-20' },
  { id: 'partner-3', name: 'Thales Canada', email: 'procurement@thales.ca', phone: '+1 416-555-0303', type: 'Integrator', status: 'active', address: 'Ottawa, ON, Canada', notes: 'Defense sector partner', blueprints: 28, totalPrints: 445, revenue: 95000, joinedDate: '2024-03-10' },
  { id: 'partner-4', name: 'Equinor Canada', email: 'sourcing@equinor.com', phone: '+1 709-555-0404', type: 'OEM', status: 'active', address: "St. John's, NL, Canada", notes: 'Bay du Nord project partner', blueprints: 23, totalPrints: 567, revenue: 85000, joinedDate: '2024-03-25' },
  { id: 'partner-5', name: 'Horizon Maritime', email: 'operations@horizonmaritime.ca', phone: '+1 902-555-0505', type: 'Service Provider', status: 'active', address: 'Halifax, NS, Canada', notes: 'Primary beta tester for pilot program', blueprints: 18, totalPrints: 324, revenue: 48500, joinedDate: '2024-04-01' },
  { id: 'partner-6', name: 'Cove Energy', email: 'supply@coveenergy.com', phone: '+1 780-555-0606', type: 'Distributor', status: 'pending', address: 'Edmonton, AB, Canada', notes: 'New partner - pending verification', blueprints: 12, totalPrints: 89, revenue: 13400, joinedDate: '2024-06-15' },
  { id: 'partner-7', name: 'Wärtsilä Canada', email: 'parts@wartsila.com', phone: '+1 604-555-0707', type: 'OEM', status: 'active', address: 'Vancouver, BC, Canada', notes: 'Marine propulsion systems specialist', blueprints: 35, totalPrints: 678, revenue: 102000, joinedDate: '2024-02-01' },
  { id: 'partner-8', name: 'Ecotex Industries', email: 'procurement@ecotex.ca', phone: '+1 867-555-0808', type: 'Integrator', status: 'inactive', address: 'Yellowknife, NT, Canada', notes: 'Arctic utility components - account on hold', blueprints: 8, totalPrints: 45, revenue: 6750, joinedDate: '2024-01-20' },
]

export const materials = [
  { id: 'mat-1', name: 'Titanium Ti-6Al-4V', category: 'Metal Powder', totalStock: 450, unit: 'kg', minStock: 200, maxStock: 1000, reorderPoint: 300, status: 'adequate', unitCost: 450, leadTime: 14, centerStocks: [{ centerName: 'Atlantic XL', stock: 200 }, { centerName: 'LR Montreal', stock: 150 }, { centerName: 'Victoria Marine', stock: 100 }] },
  { id: 'mat-2', name: 'Stainless Steel 316L', category: 'Metal Powder', totalStock: 680, unit: 'kg', minStock: 300, maxStock: 1500, reorderPoint: 400, status: 'adequate', unitCost: 120, leadTime: 7, centerStocks: [{ centerName: 'Atlantic XL', stock: 300 }, { centerName: 'DNV Calgary', stock: 200 }, { centerName: 'LR Montreal', stock: 180 }] },
  { id: 'mat-3', name: 'Aluminum 6061-T6', category: 'Metal Powder', totalStock: 150, unit: 'kg', minStock: 200, maxStock: 800, reorderPoint: 250, status: 'low', unitCost: 85, leadTime: 5, centerStocks: [{ centerName: 'Atlantic XL', stock: 80 }, { centerName: 'Victoria Marine', stock: 70 }] },
  { id: 'mat-4', name: 'Inconel 718', category: 'Metal Powder', totalStock: 280, unit: 'kg', minStock: 150, maxStock: 600, reorderPoint: 200, status: 'adequate', unitCost: 680, leadTime: 21, centerStocks: [{ centerName: 'DNV Calgary', stock: 180 }, { centerName: 'LR Montreal', stock: 100 }] },
  { id: 'mat-5', name: 'H13 Tool Steel', category: 'Metal Powder', totalStock: 90, unit: 'kg', minStock: 100, maxStock: 400, reorderPoint: 150, status: 'critical', unitCost: 220, leadTime: 10, centerStocks: [{ centerName: 'DNV Calgary', stock: 60 }, { centerName: 'Atlantic XL', stock: 30 }] },
  { id: 'mat-6', name: 'Steel 4340', category: 'Metal Powder', totalStock: 520, unit: 'kg', minStock: 200, maxStock: 1000, reorderPoint: 300, status: 'adequate', unitCost: 95, leadTime: 7, centerStocks: [{ centerName: 'DNV Calgary', stock: 300 }, { centerName: 'Atlantic XL', stock: 220 }] },
  { id: 'mat-7', name: 'Copper C18150', category: 'Metal Powder', totalStock: 120, unit: 'kg', minStock: 80, maxStock: 300, reorderPoint: 100, status: 'adequate', unitCost: 180, leadTime: 12, centerStocks: [{ centerName: 'LR Montreal', stock: 120 }] },
  { id: 'mat-8', name: 'Bronze C95400', category: 'Metal Powder', totalStock: 75, unit: 'kg', minStock: 100, maxStock: 400, reorderPoint: 150, status: 'low', unitCost: 150, leadTime: 10, centerStocks: [{ centerName: 'Victoria Marine', stock: 75 }] },
]

export const certifications = [
  { id: 'cert-1', name: "Lloyd's Register Type Approval", type: 'Type Approval', issuer: "Lloyd's Register", holder: 'Atlantic XL', status: 'active', issueDate: '2023-06-15', expiryDate: '2026-06-14', scope: 'Marine structural and critical components - Metal AM', documentUrl: '/certs/lr-atlantic-xl.pdf' },
  { id: 'cert-2', name: 'DNV GL Part 6 Certification', type: 'Part Certification', issuer: 'DNV GL', holder: 'DNV Calgary', status: 'active', issueDate: '2023-08-20', expiryDate: '2026-08-19', scope: 'Offshore components - High-temperature materials', documentUrl: '/certs/dnv-calgary.pdf' },
  { id: 'cert-3', name: "Lloyd's Register Type Approval", type: 'Type Approval', issuer: "Lloyd's Register", holder: 'LR Montreal', status: 'active', issueDate: '2024-01-10', expiryDate: '2027-01-09', scope: 'Thermal components and heat exchangers', documentUrl: '/certs/lr-montreal.pdf' },
  { id: 'cert-4', name: 'CSA Certification', type: 'Product Certification', issuer: 'CSA Group', holder: 'Victoria Marine', status: 'active', issueDate: '2023-09-01', expiryDate: '2025-08-31', scope: 'Electrical enclosures and control panels', documentUrl: '/certs/csa-victoria.pdf' },
  { id: 'cert-5', name: 'DNV GL Part 6 Certification', type: 'Part Certification', issuer: 'DNV GL', holder: 'Atlantic XL', status: 'active', issueDate: '2023-11-15', expiryDate: '2026-11-14', scope: 'Subsea components - Titanium alloys', documentUrl: '/certs/dnv-atlantic-xl.pdf' },
  { id: 'cert-6', name: 'ISO 13485 Medical Devices', type: 'Quality Management', issuer: 'BSI', holder: 'Atlantic XL', status: 'pending', issueDate: '2024-06-01', expiryDate: '2027-05-31', scope: 'Medical device component manufacturing (pending audit)', documentUrl: null },
  { id: 'cert-7', name: "Lloyd's Register Type Approval", type: 'Type Approval', issuer: "Lloyd's Register", holder: "St. John's AM", status: 'expired', issueDate: '2021-03-20', expiryDate: '2024-03-19', scope: 'Emergency marine components', documentUrl: '/certs/lr-stjohns.pdf' },
  { id: 'cert-8', name: 'AS9100D Aerospace', type: 'Quality Management', issuer: 'SAI Global', holder: 'DNV Calgary', status: 'expiring_soon', issueDate: '2022-04-01', expiryDate: '2025-03-31', scope: 'Aerospace component manufacturing', documentUrl: '/certs/as9100-calgary.pdf' },
]

export const auditLogs = [
  { id: 'log-1', orderId: 'ord-1', action: 'ORDER_CREATED', details: 'Order ORD-2847 created for Thruster Bearing Housing', userId: 'user-1', createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2847', partName: 'Thruster Bearing Housing' } },
  { id: 'log-2', orderId: 'ord-1', action: 'ORDER_UPDATED', details: 'Order ORD-2847 status changed to printing', userId: null, createdAt: new Date(Date.now() - 0.8 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2847', partName: 'Thruster Bearing Housing' } },
  { id: 'log-3', orderId: 'ord-2', action: 'ORDER_CREATED', details: 'Order ORD-2846 created for Hydraulic Valve Body', userId: 'user-2', createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2846', partName: 'Hydraulic Valve Body' } },
  { id: 'log-4', orderId: 'ord-2', action: 'ORDER_UPDATED', details: 'Order ORD-2846 status changed to quality_check', userId: null, createdAt: new Date(Date.now() - 1.5 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2846', partName: 'Hydraulic Valve Body' } },
  { id: 'log-5', orderId: 'ord-3', action: 'ORDER_CREATED', details: 'Order ORD-2845 created for Sensor Mounting Bracket', userId: 'user-3', createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2845', partName: 'Sensor Mounting Bracket' } },
  { id: 'log-6', orderId: 'ord-3', action: 'ORDER_UPDATED', details: 'Order ORD-2845 status changed to shipped', userId: null, createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2845', partName: 'Sensor Mounting Bracket' } },
  { id: 'log-7', orderId: 'ord-4', action: 'ORDER_CREATED', details: 'Order ORD-2844 created for Impeller Shaft', userId: 'user-1', createdAt: new Date(Date.now() - 0.5 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2844', partName: 'Impeller Shaft' } },
  { id: 'log-8', orderId: 'ord-5', action: 'ORDER_CREATED', details: 'Order ORD-2843 created for Heat Exchanger Plate', userId: 'user-2', createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2843', partName: 'Heat Exchanger Plate' } },
  { id: 'log-9', orderId: 'ord-5', action: 'ORDER_UPDATED', details: 'Order ORD-2843 status changed to delivered', userId: null, createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2843', partName: 'Heat Exchanger Plate' } },
  { id: 'log-10', orderId: 'ord-6', action: 'ORDER_CREATED', details: 'Order ORD-2842 created for Pressure Housing Seal', userId: 'user-1', createdAt: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2842', partName: 'Pressure Housing Seal' } },
  { id: 'log-11', orderId: 'ord-6', action: 'ORDER_UPDATED', details: 'Order ORD-2842 status changed to printing', userId: null, createdAt: new Date(Date.now() - 0.8 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2842', partName: 'Pressure Housing Seal' } },
  { id: 'log-12', orderId: 'ord-7', action: 'ORDER_CREATED', details: 'Order ORD-2841 created for Motor Coupling Flange', userId: 'user-3', createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(), order: { orderId: 'ORD-2841', partName: 'Motor Coupling Flange' } },
]

export const dashboardStats = {
  totalOrders: orders.length,
  activeOrders: orders.filter(o => ['pending', 'printing', 'quality_check'].includes(o.status)).length,
  deliveredParts: orders.filter(o => o.status === 'delivered').reduce((sum, o) => sum + o.quantity, 0),
  avgLeadTime: 4.2,
  costSavings: orders.filter(o => o.status === 'delivered').reduce((sum, o) => sum + o.quantity * 150, 0),
  totalBlueprints: blueprints.length,
  activeCenters: printCenters.filter(c => c.status === 'online').length,
}
